# Generated by Django 5.2.2 on 2025-06-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_payments', '0001_initial'),
        ('hotel_rooms', '0014_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_rooms.hotel'),
        ),
    ]
