# Generated by Django 5.2.2 on 2025-06-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_payments', '0002_alter_booking_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
    ]
