# Generated by Django 5.2.2 on 2025-07-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_payments', '0003_remove_booking_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
