# Generated by Django 5.2.2 on 2025-06-10 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('star_rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('suit', 'suit'), ('dormitory', 'dormitory')], default='AC', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_booked', models.BooleanField(default=True)),
                ('room_image', models.ManyToManyField(blank=True, to='hotel_rooms.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('hotel_image', models.ImageField(upload_to='media')),
                ('address', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('location', models.CharField(choices=[('dshala', 'Dharamshala'), ('mnali', 'Manali'), ('kullu', 'Kullu'), ('baijnath', 'Baijnath'), ('hmirpur', 'Hamirpur'), ('kangra', 'Kangra'), ('chamba', 'Chamba'), ('jwalaji', 'Jawalaji'), ('nadaun', 'Nadaun'), ('ranikhet', 'Ranikhet'), ('athankot', 'Pathankot'), ('gaggal', 'Gaggal'), ('shahpur', 'Shahpur')], default='Dharamshala', max_length=50)),
                ('facilities', models.CharField(choices=[('wifi', 'Wi-Fi'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('parking', 'Parking'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry Service'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('spa', 'Spa'), ('pet_friendly', 'Pet Friendly'), ('kids_play_area', 'Kids Play Area'), ('game_room', 'Game Room'), ('meeting_room', 'Meeting Room')], default='wifi', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ManyToManyField(blank=True, related_name='hotel_review', to='hotel_rooms.review')),
                ('room', models.ManyToManyField(blank=True, related_name='hotel_room', to='hotel_rooms.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
