# Generated by Django 5.2.2 on 2025-06-10 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('facilities', models.CharField(choices=[('wifi', 'Wi-Fi'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('parking', 'Parking'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry Service'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('spa', 'Spa'), ('pet_friendly', 'Pet Friendly'), ('kids_play_area', 'Kids Play Area'), ('game_room', 'Game Room'), ('meeting_room', 'Meeting Room')], default='wifi', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facility',
            field=models.ManyToManyField(related_name='hotel_facilities', to='hotel_rooms.facilities'),
        ),
    ]
