# Generated by Django 5.2.2 on 2025-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0002_facilities_remove_hotel_facilities_hotel_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='facility',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.CharField(choices=[('wifi', 'Wi-Fi'), ('pool', 'Swimming Pool'), ('gym', 'Gym'), ('parking', 'Parking'), ('ac', 'Air Conditioning'), ('laundry', 'Laundry Service'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('spa', 'Spa'), ('pet_friendly', 'Pet Friendly'), ('kids_play_area', 'Kids Play Area'), ('game_room', 'Game Room'), ('meeting_room', 'Meeting Room')], default='wifi', max_length=50),
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
