# Generated by Django 5.2.2 on 2025-06-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0005_hotel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
    ]
