# Generated by Django 5.2.2 on 2025-06-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0006_remove_hotel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_rooms.hotel'),
        ),
    ]
