# Generated by Django 5.2.2 on 2025-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0007_remove_hotel_review_review_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='hotel_review', to='hotel_rooms.review'),
        ),
    ]
