# Generated by Django 5.2.2 on 2025-06-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0008_remove_review_hotel_hotel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(null=True),
        ),
    ]
