# Generated by Django 5.2.2 on 2025-06-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0010_alter_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
    ]
