# Generated by Django 5.2.2 on 2025-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0011_remove_hotel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='hotel_review', to='hotel_rooms.review'),
        ),
    ]
