# Generated by Django 5.2.2 on 2025-06-30 06:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0014_alter_room_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_rooms.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
