# Generated by Django 5.2.2 on 2025-07-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_rooms', '0015_remove_hotel_review_review_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
    ]
