# Generated by Django 5.2.1 on 2025-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('Under maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel/hotel_image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_image',
            field=models.ImageField(upload_to='hotel/room_image'),
        ),
    ]
