# Generated by Django 5.2.1 on 2025-06-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_status_alter_hotelimage_hotel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'standard'), ('deluxe', 'deluxe'), ('suit', 'suit'), ('dormitory', 'dormitory')], default='AC', max_length=50),
        ),
    ]
