# Generated by Django 5.2.1 on 2025-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel_image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_image',
            field=models.ImageField(upload_to='room_image'),
        ),
    ]
