# Generated by Django 5.2.1 on 2025-06-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotelimage_hotel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='room',
            field=models.ManyToManyField(blank=True, to='hotel.room'),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelimage'),
        ),
    ]
