# Generated by Django 5.2.1 on 2025-06-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_room_hotel_hotel_room_and_more'),
        ('hotel_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Location',
        ),
    ]
