# Generated by Django 5.2.1 on 2025-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_destination_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
